### ISSUE TITLE
Captcha not solving

### ISSUE THREAD

**Issue by TodesAnge1** [hnavidan/VFSBot#1]
The problem with captcha solving, the window opens and closes endlessly, apparently the captcha cannot be solved. And so it continues more than 30-40 times. Any ideas what could be the problem?

**Comment by hnavidan** [comment]
Hey,

I am aware that the captcha-solving algorithm isn't efficient, and it takes several attempts (sometimes up to 20-30) to crack it successfully. However, our country's version of the VFS site has no restriction on the number of attempts (for now), and this approach works. From what I've seen, VFS uses different captchas in different countries. This is the version this script was built for:

![captcha](https://user-images.githubusercontent.com/942306/187032216-a9a14566-4d1b-419f-87e6-2771ad9fa361.png)

**Comment by hnavidan** [comment]
The captcha recognition should be improved with 5be988803b9f5560ea1b187b8a31bc848866e29b. However, if you still need 100% accurate recognition, I recommend using 2Captcha (which is not free.)

**Comment by ataberkw** [comment]
Turkey has reCaptcha. I don't think it can solve reCaptcha.
<img width="404" alt="image" src="https://user-images.githubusercontent.com/10375421/236576532-1b9fc2b6-bf01-4b01-b8c5-f601884f9072.png">

**Comment by wasimekram** [comment]
@hnavidan Can you provide the code for 2captcha in another branch?

**Comment by hnavidan** [comment]
> @hnavidan Can you provide the code for 2captcha in another branch?

It should be something like this:

1- You define self.solver and enter the API key in __init__ method of the class:
`self.solver = TwoCaptcha(config.get('2CAPTCHA', 'api_key'))`

2- Then you break the captcha. SITE_KEY is a unique constant code that can be obtained via inspect element. 

`captcha_input = self.browser.find_element(By.ID, 'g-recaptcha-response')
 try:
     result = self.solver.recaptcha(sitekey='SITE_KEY', url=self.url)
  except Exception as e:
     print(e)
  
  self.browser.execute_script("arguments[0].setAttribute('style','type: text; visibility:visible;');", captcha_input)
  captcha_input.send_keys(result.get('code'))`
