### ISSUE TITLE
Endless login for VFS Russia

### ISSUE THREAD

**Issue by AstFreelancer** [hnavidan/VFSBot#10]
The bot is working, but when it's trying to log in, it gets this message.
![login](https://user-images.githubusercontent.com/26811216/232743996-e92ede40-6862-4cae-b0f5-d6a223b745c7.PNG)
If I check the checkbox by hand, the captcha returns and so on.

**Comment by hnavidan** [comment]
This is a different captcha implemented by Cloudflare itself. Please check if using the undetected-chromedriver in the new version of the bot bypasses it. Otherwise, you will have to change the script.

**Comment by diptilenka** [comment]
I changed to latest version  of pyteseract but now its shown i am not a robot screen.
