### ISSUE TITLE
VFS portugal in uk

### ISSUE THREAD

**Issue by gharding45** [hnavidan/VFSBot#12]
Hello. I have set up the bot and telegram which seems to be working.

However once starting, the bot only opens the login page and nothing happens. What is required to change for the following website?
https://visa.vfsglobal.com/gbr/en/prt/application-detail

Thank you

**Comment by hnavidan** [comment]
Please read the readme. The login page of the VFS is different (probably a newer version) and also uses recpatcha. You will have to modify and adapt the script.
