### ISSUE TITLE
dependemcies issues

### ISSUE THREAD

**Issue by geojasse** [hnavidan/VFSBot#14]
i installed new dependencies, but had an issue with the handler and would receive errors. I installed the older dependency but I'm still having issues running the code. I'm completely new to coding, so if you could give me a detailed step by step guide, that would be helpful, 
![image](https://github.com/hnavidan/VFSBot/assets/139579961/e606a82b-c94a-42c4-91e5-66ff3129f69a)

![image](https://github.com/hnavidan/VFSBot/assets/139579961/03afcfa1-ca3c-4278-9cf7-2e8c245a28f3)

**Comment by hnavidan** [comment]
Looks like an issue with your environment.
