### ISSUE TITLE
Cloudfare screen stuck to verify as human

### ISSUE THREAD

**Issue by diptilenka** [hnavidan/VFSBot#19]
The screen stucks here 
![Screenshot 2023-12-12 180852](https://github.com/hnavidan/VFSBot/assets/63293480/d1f99a3b-8646-4f9b-931b-e5d061233ea2)

how to solve this screen

**Comment by Ali-Flt** [comment]
I also get this:
![image](https://github.com/hnavidan/VFSBot/assets/60854595/14408798-7f1f-48e3-8b1a-bae10808008a)

Any idea how we may solve this? It seems like the VFS website is very sensitive to too many requests and also bot connections

**Comment by hnavidan** [comment]
Some countries use Cloudflare. For that, you need to use paid services such as twocaptcha. You can read more about 2captcha on their [website](https://2captcha.com/).

**Comment by mparadise12** [comment]
I didn't slove my problem please prove me your what's app number
