### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by The-Yooniverse** [hnavidan/VFSBot#3]
Hello, I am trying for Poland VFS from India and after configuring the script, nothing happens, the cursor keeps blinking.
In my bot, I get a message, "Unauthorized access"

What should I put here?
admin_ids = 

These are my links:
https://visa.vfsglobal.com/ind/en/pol/book-an-appointment

https://row2.vfsglobal.com/GAPolandAppt/Account/RegisteredLogin?q=shSA0YnE4pLF9Xzwon/x/ASnHZRMROGDyz5YljrTPrmbws9m3YKnjDXuh/15KyMksdtUgr/FOny2C0bQ3U4uiw==

I checked the XPATH and it seems to be the same as the one in your script.

I can't get it to work, hope you can help, I can share credentials if needed, thanks a lot!

**Comment by hereisash** [comment]
Hi @The-Yooniverse 

you have to put your own channel id from username_to_id_bot. It worked for me.
Although, my scrpit fails to verify as human while loading webpage, I am waiting for @hnavidan 's comment on it.

**Comment by nikhilkumar13199** [comment]
Hi @The-Yooniverse @hereisash , were you able to find a working solution for this problem?

**Comment by The-Yooniverse** [comment]
> Hi @The-Yooniverse @hereisash , were you able to find a working solution for this problem?

Nope, just checking for slots time to time on the official page. :(

**Comment by hnavidan** [comment]
@hereisash, the problem with Cloudflare firewall should be fixed in 5be988803b9f5560ea1b187b8a31bc848866e29b.
