### ISSUE TITLE
script runs into error

### ISSUE THREAD

**Issue by hereisash** [hnavidan/VFSBot#4]
Hi,

thanks for the script, I am trying to run it windows 11 and trying for VFS Poland.
this site always needs to be opened in incognito mode so I added this line in your code.
self.options.add_argument("--incognito")

 But it gets stuck on below part

<img width="662" alt="image" src="https://user-images.githubusercontent.com/123172313/213864569-a55c35e2-2fa4-4a00-a819-c06b45aaa897.png">

**Comment by hnavidan** [comment]
Looks like they've added cloudflare captcha. You need to find some methods of bypassing the captcha.
