### ISSUE TITLE
Captcha not solving

### ISSUE THREAD

**Issue by anovob** [hnavidan/VFSBot#5]
Please check my image which was not solve
![captcha](https://user-images.githubusercontent.com/5115489/213945715-e9b35008-6313-420b-9bc2-9367f4603a95.png)
![captcha](https://user-images.githubusercontent.com/5115489/213945778-5d24410c-2f4e-4094-98cf-2c1d18193f7b.png)

**Comment by hnavidan** [comment]
https://github.com/hnavidan/VFSBot/issues/1

**Comment by hnavidan** [comment]
Duplicate: 
https://github.com/hnavidan/VFSBot/issues/1
