### ISSUE TITLE
Is it working ?

### ISSUE THREAD

**Issue by Sicks3c** [hnavidan/VFSBot#7]
Hello

Thank you for the script
Trying to get an appointment for Portugal and I'm running it from VPS

<img width="507" alt="Screenshot 2023-02-11 at 23 55 10" src="https://user-images.githubusercontent.com/32225186/218284552-1eadac1d-dac0-4648-89bb-ad56b35f26da.png">
How to confirm if this is working or not

Cheers

**Comment by hnavidan** [comment]
Please read the readme. You have to connect it to a Telegram bot to see the logging messages. For best results, it is better to run and debug your version of the script on your local machine with Chrome GUI so you can see what goes wrong.
