### ISSUE TITLE
cannot import handler

### ISSUE THREAD

**Issue by kaushal-cmyk** [hnavidan/VFSBot#8]

**Comment by kaushal-cmyk** [comment]
utilis.py file cannot import handler from python-telegram-bot.
Anyone knows how to fix this.

**Comment by gomesprince** [comment]
@kaushal-cmyk  I had similar issue. I got around this issue by setting dependencies versions as per requirements.txt. 
pip install selenium==3.141.0
pip install selenium-stealth==1.0.6
pip install opencv-python==4.5.5.64
pip install tesseract==0.1.3
pip install pytesseract==0.3.9
pip install python-telegram-bot==13.11

I was able to run it successfully but it does nothing. Maybe I am missing something. Hope you will find this helpful.

**Comment by hnavidan** [comment]
Indeed, the python-telegram-bot version should be 13.11. You are using a newer version.
